### PR TITLE
Python Support

### LINKED ISSUE #29: Python Support
As seen here #27
Messed up and accidentally merged early.

### PR DESCRIPTION
**Pull request by braxtonhall**
Resolves #29

### CODE REVIEW

**Comment by braxtonhall** [comment]
please squash this
there is too much garbage in these commits for such a smol task

**Comment by rtholmes** [comment]
Actually @braxtonhall I'd like to merge this into the `origin/research` branch because this (with the other lang support and annotations from #1 ) will be the basis of code shovel v2, rather than the v1 work which will be in master until v2 is done!

**Comment by rtholmes** [comment]
(but if you want to make sure this is up-to-date with master we could actually just make this the research branch (which may have been deleted) and pull #1 into it.

**Comment by braxtonhall** [comment]
Which one is the research branch?

**Comment by rtholmes** [comment]
It's what Felix wanted to call the WIP branch. But maybe `dev` or `develop` would be better (aka one does not exist, you could just start one with this!).

**Comment by ishtiaque05** [comment]
@braxtonhall are we then using the `develop` branch as the research branch? If @rtholmes is done putting content in his `reid_icse2021` branch then we can update the `develop` branch with the latest content from `reid_icse2021` and start `v2` from there?

**Comment by braxtonhall** [comment]
Yup! Sounds perfect @ishtiaque05

**Comment by rtholmes** [comment]
I think the main thing that needs to happen @ishtiaque05 is pulling `reid_icse2021` into the `develop` branch. Right now `develop` is quite behind. Once that's done it will be easy to keep up-to-date in the future.

**Pull request merged**
