### PR TITLE
Annotation Change

### LINKED ISSUE #1: Handle Annotations
Java Annotations are currently ignored. But they can be an essential part of methods. We should look into how we could deal with them.

### PR DESCRIPTION
**Pull request by braxtonhall**
resolves #1

### CODE REVIEW

**Comment by braxtonhall** [comment]
Turns out it was really common because all these tests need to get fixed before we merge 🤦‍♀️ 
Screen Shot 2021-02-18 at 5 18 46 PM

**Comment by braxtonhall** [comment]
Tests have been updated. Some of the 10 failing `Z_*` tests may need further updating, as my process involved first running CodeShovel and then verifying these changes in GitHub.

**Comment by rtholmes** [comment]
@braxtonhall lgtm. I think my main concern is that `AbstractParser` doesn't take `AnnotationChange` into account at all during the similarity matching, but that is something that we can think about more in the future (I'm not saying it _should_ but it is something to think about in the future).

**Review by rtholmes — APPROVED** [review]
lgtm. We can think about how annotations should roll into the matching algorithm in the future.

**Comment by braxtonhall** [comment]
Oh I put it in under `getMinorChanges`, and I think none of the minor changes are considered for the similarity algorithm :)

**Pull request merged**
