### PR TITLE
Feature ataraxie/codeshovel#64: Extend CodeShovel to capture JavaDoc

### PR DESCRIPTION
**Pull request by ishtiaque05**
- Add a json key `functionJavaDoc` which contains the java doc string
TODO: implement "getInitialJavaDoc" for python and typescript
- For python implement here: PythonFunction.java
- For typescript implement here: TypeScriptFunction.java
Discussion link: ataraxie/codeshovel#64

### CODE REVIEW

**Comment by ishtiaque05** [comment]
I realized `getInitialJavaDoc` is a poor choice of name  and should be change to `getInitialDoc`

**Comment by ishtiaque05** [comment]
- Add a new change type `Ydocchange` which extends `Ysignaturechange`
- Rename everywhere reference of *javaDoc* -> Doc to keep things consistent with python
  and typescript implementation
TODO list:
- [ ]  Implement `getInitialDoc` in `com/felixgrund/codeshovel/parser/impl/PythonFunction.java`
- [ ] Implement `getInitialDoc` in `com/felixgrund/codeshovel/parser/impl/TypeScriptFunction.java`
- [ ] Handle `Ydocchange` in `src/main/java/com/felixgrund/codeshovel/parser/impl/TypeScriptParser.java`
- [ ] Handle `Ydocchange` in `src/main/java/com/felixgrund/codeshovel/parser/impl/PythonParser.java`
- [ ] Get the diff for doc changes
- [ ] Run `mvn test` and fix some test

**Comment by braxtonhall** [comment]
I'm realizing that this may be a bigger change than the annotation change. We would probably want to use javadoc in the similarity algorithm.

**Comment by ishtiaque05** [comment]
> I'm realizing that this may be a bigger change than the annotation change. We would probably want to use javadoc in the similarity algorithm.
Is this because you want to track `JavadocBlockTag` such as `PARAM`, `RETURN`, `THROWS` etc?

Example of a proper `javadoc` with all its element block tag:

```
/**
	 * Subject line
	 *
	 * <p>Description of the method with optional {@code code} and {@link Object links to Javadoc}
	 * </p>
	 *
	 * <pre>
	 *    raw input
	 * </pre>
	 *
	 * @param foo first arg
	 * @return a bar
	 * @throws SomeException if bar goes wrong
	 * @see someOtherMethod()
	 * @since 2.2.2
	 * @author me
	 */
```

**Comment by ishtiaque05** [comment]
Finally, I was able to run test locally 🎉  and now we have `Ydocchange` test failures.  I will fix them and push it 😃 

Ydocchange

**Comment by braxtonhall** [comment]
> > I'm realizing that this may be a bigger change than the annotation change. We would probably want to use javadoc in the similarity algorithm.
> 
> Is this because you want to track `JavadocBlockTag` such as `PARAM`, `RETURN`, `THROWS` etc changes?
> 
> Example of a proper `javadoc` with all its element block tag:
> 
> ```
> /**
> 	 * Subject line
> 	 *
> 	 * <p>Description of the method with optional {@code code} and {@link Object links to Javadoc}
> 	 * </p>
> 	 *
> 	 * <pre>
> 	 *    raw input
> 	 * </pre>
> 	 *
> 	 * @param foo first arg
> 	 * @return a bar
> 	 * @throws SomeException if bar goes wrong
> 	 * @see someOtherMethod()
> 	 * @since 2.2.2
> 	 * @author me
> */
> ```

Sorry should have replied here 😅 

I think the description of the method may be useful in discerning if two methods match or are "the same method".
It seems like it would be wasteful to not account for the Javadoc in the similarity calculation

**Comment by rtholmes** [comment]
@ishtiaque05 great work with this PR. It's really interesting to see how pervasive doc changes are (and how they do (and do not) line up with other kinds of changes.

**Comment by ishtiaque05** [comment]
Hi, could we merge this with the `develop` branch and work on `Javadoc` as a part of the similarity algorithm and get the `diff` in a separate issue, please?

**Review by rtholmes — APPROVED** [review]
lgtm

**Pull request merged**
